### ISSUE TITLE
Add org wide funding file

### ISSUE THREAD

**Issue by MattIPv4** [alveusgg/.github#1]
Add an org-wide funding file with Alveus' info in it.

I believe GitHub has native support for PayPal, and then we can provide a custom link to the website donate page.

**Comment by pjeweb** [comment]
> I believe GitHub has native support for PayPal

they removed paypal not that long ago https://github.blog/changelog/2023-01-23-github-sponsors-will-stop-supporting-paypal/

**Comment by MattIPv4** [comment]
Ah yeah, looks like https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository doesn't have PayPal.

We can just do a custom link to the site donate page then
